# Same MSYS2 MinGW64 compiler and Ninja used by TriggerFish-VCV.
set(DRUMFOUNDRY_MSYS2 "C:/msys64")
if(DEFINED ENV{MSYS2_ROOT} AND NOT "$ENV{MSYS2_ROOT}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{MSYS2_ROOT}" DRUMFOUNDRY_MSYS2)
endif()
set(DRUMFOUNDRY_BIN "${DRUMFOUNDRY_MSYS2}/mingw64/bin")
set(CMAKE_CXX_COMPILER "${DRUMFOUNDRY_BIN}/g++.exe" CACHE FILEPATH "MinGW C++" FORCE)
set(CMAKE_MAKE_PROGRAM "${DRUMFOUNDRY_BIN}/ninja.exe" CACHE FILEPATH "Ninja" FORCE)
set(ENV{PATH} "${DRUMFOUNDRY_BIN};$ENV{PATH}")
